#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# zpresto has the annoying rm -i by default.
unalias rm
# zpresto will force you to use >! and >>! instead of the default
# 'for precaution'
setopt clobber

alias ls="ls --color=auto"

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# # Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

fpath=($SHELL_FILES/completions $fpath)

setopt alwaystoend             # when complete from middle, move cursor
setopt completeinword          # not just at the end
setopt listpacked              # compact completion lists
setopt noautomenu              # don't cycle completions
setopt pushdignoredups         # and don't duplicate them
setopt recexact                # recognise exact, ambiguous matches
setopt nullglob
setopt sharehistory
setopt histverify              # when using ! cmds, confirm first
setopt correct                 # spelling correction
setopt rmstarwait              # if `rm *` wait 10 seconds before performing it!
setopt notify                  # notify of BG job completion immediately
setopt printexitvalue          # alert me if something's failed
setopt autocd                  # change to dirs without cd
setopt autopushd               # automatically append dirs to the push/pop list
setopt cdablevars              # avoid the need for an explicit $
setopt nobeep                  # i hate beeps
setopt nohup                   # and don't kill BG jobs when shell exits
setopt extendedglob            # awesome pattern matching (ala Dir.glob() in Ruby)
setopt promptcr                # ensure a new line before prompt is drawn
setopt listtypes               # show types in completion
setopt nocompletealiases       # Allows alias 'ga' to use 'git add' completions (for example)
setopt interactivecomments     # escape commands so i can use them later
setopt sh_word_split           # commands will be split on space (i.e. $VISUAL = "mate -wl1" will work)

# Allow kill word and moving forward/backword by word to behave like bash (e.g. stop at / chars)
autoload -U select-word-style
select-word-style bash

if [[ -s ~/.zshrc-local ]]; then
  source ~/.zshrc-local
fi
